### PR TITLE
may 2022 image search refresh

### PR DESCRIPTION
**Pull request by startakovsky**
- Test image present
- Image Search Example Initial Commit

### CODE REVIEW

**Comment by startakovsky** [comment]
@gkogan @jamescalam 

Tomorrow, I will address the comments from @jamescalam (thank you James) and submit modifications therein for Semantic Search and Jeopardy. Once those are done and merged upstream to the Pinecone repository, I will iterate on Image Search. In the meantime, please have a look and supply your review. The notebook should take less than 15 minutes to run, and we can truncate as per @jamescalam's recommendations.

**Comment by startakovsky** [comment]
Once https://github.com/pinecone-io/examples/pull/59 is merged @jamescalam @gkogan, I will add a Colab badge and it will be updated accordingly when merged to pinecone-io/master.

**Comment by jamescalam** [comment]
Awesome notebook @startakovsky - I left a [couple of minor comments](https://app.reviewnb.com/startakovsky/pinecone-examples-fork/blob/may-2022-image-search-refresh/image_search%2Fimage_search.ipynb%2F/discussion)

**Review by jamescalam — CHANGES_REQUESTED** [review]
Awesome notebook @startakovsky - I left a [couple of minor comments](https://app.reviewnb.com/startakovsky/pinecone-examples-fork/blob/may-2022-image-search-refresh/image_search%2Fimage_search.ipynb%2F/discussion)

**Review by jamescalam — COMMENTED** [review]
@startakovsky looks great, thanks for adding those comments. One more thing, when I ran this notebook in colab earlier it took ~50 mins to encode the two CIFAR datasets - was the ~15 minutes you mentioned earlier on colab?

**Comment by startakovsky** [comment]
@jamescalam No, it was on my M1 Macbook 😞 (2021). What is your recommendation? Also, is Colab usually pretty slow in your experience?

**Comment by jamescalam** [comment]
@startakovsky could you add a parameter somewhere that allows the user to easily adjust the number of rows from CIFAR? 

Let's leave the parameter to use the full dataset, but note it as an option for any users that are in a rush

**Review by jamescalam — COMMENTED** [review]
@startakovsky could you add a parameter somewhere that allows the user to easily adjust the number of rows from CIFAR? 

Let's leave the parameter to use the full dataset, but note it as an option for any users that are in a rush

**Review by jamescalam — APPROVED** [review]
That's great, thanks @startakovsky - can merge unless @gkogan has any further feedback

**Comment by startakovsky** [comment]
Thanks @jamescalam I'll go ahead and merge and re-open a new one on https://github.com/pinecone-io/examples.

**Pull request merged**
