### PR TITLE
Do-it-yourself Jeopardy Board Curation with Pinecone

### PR DESCRIPTION
**Pull request by startakovsky**
- Jeopardy Deliverable -- no longer used for Semantic Search
- Jeopardy Deliverable Initial Draft
- Update images and imports to use jeopardy branch

Notes after approval from Greg:
 1) Update image and module references to point to pinecone-io/examples master branch

### CODE REVIEW

**Comment by gkogan** [comment]
@startakovsky couldn't run this notebook due to this error: https://capture.dropbox.com/LvCVpYfpJxTwbFpI

**Comment by startakovsky** [comment]
> @startakovsky couldn't run this notebook due to this error: https://capture.dropbox.com/LvCVpYfpJxTwbFpI

@gkogan This should work now.

**Comment by jamescalam** [comment]
Hey @startakovsky, I added a few minor tweaks, feel free to modify or ask about these changes if there's anything you think could be done better. I haven't been through the full notebook as I get a `ProtocolError` when running the async upsert function `async_results = upload_dataframe_to_pinecone_in_chunks(df, index, model)`. Have you seen this before?

**Comment by startakovsky** [comment]
@jamescalam Thanks for taking a look at this stuff. I haven't seen it before. Can you confirm that authentication with Pinecone successful? Also, are you running this locally, or in Colab?

**Comment by startakovsky** [comment]
@jamescalam What is the exact error you got? I just got another error on my machine that also says Protocol Error for something else I'm doing. It's either a connection issue on my end or on the server side. Here's a screenshot for what it's worth: 
image

**Comment by startakovsky** [comment]
@jamescalam I think I figured it out. Check to see if you have the index up. This error is a poor descriptor of the problem. On my end on way I see this error is if I've not yet created the index.

**Review by jamescalam — COMMENTED** [review]
Cool idea, a little complex but I do like the the Jeopardy idea a lot, it's fun.

I added some limits to the dataset (while trying to keep the ancient attitudes examples working) and also an index check.

My previous problems were not issues, everything works now.

**Comment by startakovsky** [comment]
Completed Jeopardy Example, as reviewed by @jamescalam with additional tweaks and a final run-through by @startakovsky  -- cc: @gkogan

**Pull request merged**
